## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [2]:
import numpy as np

![title](./img/3_2.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [18]:
arr1 = np.array([[3,1,2],[-5,4,1],[0,3,-8]])
arr2 = np.array([[0,5,-1],[3,2,-1],[10, 0.5, 4]])

arr_res = np.multiply(arr1, arr2)
print(arr_res)

# okay numpy is great but... how would you inverse a matrix by hand?
def get_matrixMinor(m,i,j):
     return m[np.array(list(range(i))+list(range(i+1,m.shape[0])))[:,np.newaxis],
               np.array(list(range(j))+list(range(j+1,m.shape[1])))]

def inverse_matrix(A):
    determinant = np.linalg.det(A)
    if A.ndim == 2:
         res = [[A[1][1]/determinant, -1 * A[0][1]/determinant],[-1 * A[1][0]/determinant, A[0][0]/determinant]]

    res = np.empty_like(A)
    for r in range(A.ndim):
        resRow = np.empty_like(A)
        for n in range(A.ndim):
            minM = get_matrixMinor(A, r, n)
            np.append(resRow ,((-1)**(r+n)) * np.linalg.det(minM))
        np.append(res, resRow)
    res = np.matrix.transpose(res)
    for r in range(res.ndim):
        for c in range(res.ndim):
            res[r][c] = res[r][c]/determinant
    return res
inverse_matrix(arr1)

[[  0.    5.   -2. ]
 [-15.    8.   -1. ]
 [  0.    1.5 -32. ]]


array([[ 0,  0,  0],
       [ 0,  0,  3],
       [ 2,  1, -8]])

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [37]:
# Just answer using code --> easy stuff!
def output_ijf(D, i, j):
    return D[i,j]

arr1 = np.matrix([[3, 0.6, 4, -3],[-1.3, 4, 0, 8.6],[ 7, 0, -8, 0.006]])
arr2 = np.matrix([[ 3, -5.76, 45, 0],[ 2, -2, 1.3, 9],[ -9, 0, 0, 0]])
arr3 = np.matrix([[0, 1009, -66.7849, 90],[ 0, 5, 4, -0.07],[ -7.7 , 0, 0,  0]])

arrRes = arr1 + arr2 - arr3
print(arrRes)
output_ijf(arrRes, 2, 3)

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]


0.006

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?