# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
vec = np.zeros(10)
print(vec)

#### 4.  How to find the memory size of any array (★☆☆)

In [3]:
import numpy as np
values = [0] * 1024
vec = np.array(values)
print("Size in bytes of the vector: " + str(vec.nbytes))

Size in bytes of the vector: 4096


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
C:>python
>>import numpy as np
>>help(np)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
import numpy as np
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
import numpy as np
vec = np.arange(start=10, stop=50, step=1)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
import numpy as np
vec = np.arange(start=10, stop=50, step=1)
reversed_vec = vec[::-1]
print(reversed_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
import numpy as np
mtr = np.arange(9).reshape(3,3)
print(mtr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [17]:
import numpy as np
vec = np.array([1,2,0,0,4,0])
for i in vec:
    if i != 0: 
        res = np.where(vec == i) 
        print(res[0])

[0]
[1]
[4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
import numpy as np
vec = np.identity(3)
print(vec)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
import numpy as np
vec = np.random.random((3,3,3))
print(vec)

[[[0.84489962 0.56755364 0.58331907]
  [0.7925799  0.38837915 0.54637391]
  [0.82176578 0.88752275 0.75595757]]

 [[0.39414354 0.72147807 0.9953429 ]
  [0.25253072 0.99637406 0.7864608 ]
  [0.05923299 0.60337415 0.50224525]]

 [[0.27332229 0.16577042 0.98742944]
  [0.33533725 0.60913132 0.55441167]
  [0.48714047 0.72572613 0.8004743 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
import numpy as np
vec = np.random.rand(10,10)
print(vec.max())
print(vec.min())
print(vec)

0.9904014321512599
0.004784950851286829
[[0.18494353 0.34456459 0.14081722 0.18755269 0.59793019 0.74233191
  0.88497046 0.66181405 0.00908719 0.84976055]
 [0.36731289 0.04122904 0.65434425 0.28218797 0.1283568  0.36826408
  0.02812336 0.79666174 0.62992681 0.0951803 ]
 [0.4175801  0.83061839 0.39951935 0.60570914 0.66346531 0.70075465
  0.02545605 0.4156617  0.12823272 0.96117747]
 [0.98104096 0.78325766 0.70778591 0.59754978 0.01297212 0.67941472
  0.44373416 0.93627893 0.00478495 0.52862504]
 [0.35962049 0.57462354 0.01885946 0.33358394 0.27575941 0.5031932
  0.56609415 0.06442624 0.79278275 0.33543901]
 [0.81279686 0.78921585 0.56356873 0.05228568 0.8778675  0.99040143
  0.59250129 0.79365778 0.48970926 0.27974191]
 [0.94800061 0.17346119 0.73881905 0.36718035 0.11481385 0.72659999
  0.22536057 0.90100833 0.28500236 0.88983834]
 [0.30342661 0.71842033 0.66790625 0.42834884 0.87430302 0.01410883
  0.08630704 0.40418547 0.34929311 0.81789497]
 [0.92835573 0.51410324 0.2996755  0.8412

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [36]:
import numpy as np
vec = np.random.random(30)
print(vec)
print("Mean :" + str(np.mean(vec)))

[0.49676547 0.22331074 0.22762183 0.28348876 0.84397632 0.87417238
 0.79934481 0.21169023 0.74348727 0.5473629  0.53291579 0.10538296
 0.22498499 0.05964916 0.85974933 0.41782128 0.80074005 0.35418911
 0.94861425 0.03894294 0.66546097 0.94395043 0.28340387 0.09433279
 0.44547237 0.54992027 0.72946139 0.36964431 0.83042945 0.03623367]
Mean :0.4847506695144776


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [2]:
import numpy as np
i = 4
j = 5
vec = np.zeros(i*j).reshape(i, j)
vec[0] = np.ones(j)
vec[-1] = np.ones(j)
vec[:,0] = np.ones(i)
vec[:,-1] = np.ones(i)
print(vec)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [69]:
import numpy as np
vec = np.random.rand(4,4)
print(np.pad(vec, pad_width=1, mode='constant', constant_values=0))

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.164873   0.66747917 0.43711372 0.26326432 0.        ]
 [0.         0.62304488 0.53222877 0.2747655  0.30047208 0.        ]
 [0.         0.93837466 0.67897348 0.94777909 0.04118272 0.        ]
 [0.         0.14551129 0.52744769 0.98008271 0.03321419 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
false
false
nan
true
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [80]:
import numpy as np
mtr = np.zeros((5,5))
ins = np.array([1,2,3,4])
np.fill_diagonal(mtr[1:], ins)
print(mtr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [86]:
import numpy as np
mtr = np.zeros((8, 8))
mtr[1::2, ::2] = 1
mtr[::2 ,1::2] = 1
print(mtr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [3]:
import numpy as np
mtr = np.random.rand(6,7,8)
temp = np.reshape(mtr, 6*7*8)
res = np.where(mtr == (temp[99]))
print(res)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [4]:
import numpy as np
vec = np.ones(8)
vec[1::2] = 0
vec = np.tile(vec, (8, 1))
print(vec)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [120]:
import numpy as np
mtr = np.random.rand(5,5)
print(mtr)
mtr_max, mtr_min = mtr.max(), mtr.min() 
mtr = (mtr - mtr_min)/(mtr_max - mtr_min)
print(mtr)

[[0.72022101 0.53011892 0.22054684 0.1043695  0.16759487]
 [0.13695907 0.12742162 0.48333038 0.41955962 0.33360912]
 [0.5931582  0.06706996 0.99830763 0.14399946 0.1771424 ]
 [0.67499351 0.24417059 0.53012559 0.83046216 0.83188934]
 [0.36331404 0.45315382 0.52563239 0.52419102 0.8086969 ]]
[[0.70137954 0.49724037 0.16480957 0.04005372 0.10794764]
 [0.0750497  0.06480801 0.44699697 0.3785174  0.28622033]
 [0.56493444 0.         1.         0.08260995 0.11820015]
 [0.65281246 0.19017769 0.49724752 0.81976086 0.82129343]
 [0.31811866 0.41459218 0.49242255 0.49087476 0.79638846]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [122]:
import numpy as np
dt_rgba = np.dtype([('R',np.ubyte, 1),('G',np.ubyte, 1),('B',np.ubyte, 1),('A',np.ubyte, 1)])
print(dt_rgba)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [124]:
import numpy as np
a = np.random.rand(5,3)
b = np.random.rand(3,2)
res = np.matmul(a, b)
print(res)

[[0.79172048 0.40955378]
 [0.84506702 0.71163673]
 [1.0231848  0.61893837]
 [1.55588988 0.71347043]
 [1.27745345 0.66375658]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [134]:
import numpy as np
vec = np.random.rand(10)
for i in range(2,8,1):
    vec[i] = -vec[i]
print(vec)

[ 0.71774926  0.20326924 -0.39402311 -0.80727226 -0.0195869  -0.50565303
 -0.53658974 -0.53786344  0.02224805  0.02825905]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [135]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [138]:
import numpy as np
Z = np.array([1,2,3,4,5], dtype=np.integer)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z Illegal expressions

array([1., 2., 3., 4., 5.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [139]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [144]:
import numpy as np
vec = np.array([  2.60134534e-01,   7.9383540e-01,   5.6354645e-04])
vec = np.round(vec, 0)
print(vec)

[0. 1. 0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [145]:
import numpy as np
vec = np.array([1,2,3,4,5])
vecOne = np.array([4,5,6,7,8,9])
res = np.intersect1d(vec, vecOne)
print(res)

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [146]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [149]:
import datetime
print("today " + str(datetime.date.today()))
print("tomorrow " + str(datetime.date.today() + datetime.timedelta(days=1)))
print("yesterday" + str(datetime.date.today() - datetime.timedelta(days=1)))

today2020-12-07
tomorrow2020-12-08
tomorrow2020-12-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [155]:
import numpy as np
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [160]:
import numpy as np
a = np.ones(3)*1
b = np.ones(3)*2
b = np.add(a,b)
a = np.divide(a,2)
a = np.negative(a)
a = np.multiply(a, b)

print(a)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [167]:
import numpy as np
vec = np.random.rand(10)
print(np.floor(vec))
print(np.trunc(vec))
print(vec - vec%1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [170]:
import numpy as np
vec = np.zeros((5,5))
add = np.arange(5) 
vec += add
print(vec)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [172]:
import numpy as np
def my_generator():
    for i in range(10):
        yield i
#using numpy.fromiter get input from iterable objects
res = np.fromiter(my_generator(), dtype=integer)
print(res)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [196]:
import numpy as np
#using numpy.linspace get numbers from interval
res = np.linspace(0,1,num=12,dtype=float)
res = np.delete(res, np.s_[0::11])
print(res)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [197]:
import numpy as np
res = np.random.rand(10)
res = np.sort(res)
print(res)

[0.06127688 0.12280223 0.44279139 0.44830402 0.57423487 0.87825467
 0.88155411 0.91048577 0.92624709 0.98705336]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [5]:
import numpy as np
res = np.arange(5)
print(res)
res = np.add.reduce(res)
print(res)

[0 1 2 3 4]
10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
import numpy as np
vecOne = np.random.rand(10)
vecTwo = np.random.rand(10)
print(np.array_equal(vecOne,vecTwo))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [8]:
import numpy as np
vec = np.arange(10)
vec.flags.writeable = False
vec[0] = 1 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [35]:
import numpy as np
def cartToPol(vect):
    rho = np.sqrt(vect[0]**2 + vect[1]**2)
    phi = np.arctan2(vect[1], vect[0])
    res = np.append(rho, phi)
    return (res)
vec = np.arange(20)
vec = vec.reshape(10, 2)
print(vec)
for i in vec:
    vec[...] = cartToPol(i)
print(vec)

## EXERCISE TO END

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


KeyboardInterrupt: 

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
import numpy as np
vec = np.random.rand(10)
vec = np.where(vec == vec.max(), 0, vec)
print(vec)

[0.48217698 0.30393338 0.23875696 0.         0.54700655 0.63055732
 0.59701662 0.73956614 0.26092295 0.51493211]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [42]:
import numpy as np
mtr = np.zeros((5,5),[('x',float),('y',float)])
#insert interval in the grid for the interval from in 1 to 5 
mtr['x'], mtr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(mtr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)